# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Main"
license = "MIT"
licenselink = "https://github.com/patrickmurray/murray.systems/LICENSE"
description = "The personal web presence of Patrick Murray."
homepage = "https://murray.systems/"
min_version = 0.18

[author]
  name = "Patrick Murray"
  homepage = "https://murray.systems/"
