---
title: murray.systems
baseurl: 'https://murray.systems/'
copyright: 'Patrick Murray, All Rights Reserved.'

languageCode: en-us
theme: main

disableKinds:
  - taxonomy
  - taxonomyTerm


markup:
  highlight:
    # Source: https://xyproto.github.io/splash/docs/all.html
    style: bw
